### ISSUE TITLE
track-address not pushing messages

### ISSUE THREAD

**Issue by scottmillner** [mempool/mempool.js#146]
Context: `track-address` appears to have an upper limit on addresses that can be tracked

Code:
```
ws.on("open", function open() {
    addresses.forEach((address) => {
      logger.info(`Subscribing to ${address}`);
      ws.send(JSON.stringify({ "track-address": address }));
    });
  });
  ```
  
I've noticed that when the list of addresses increases, at some point messages for all addresses stop being pushed.  Is there an upper limit enforced by the api?
  
My logs show that the websocket remains open and I receive `pong` messages as expected but no messages are received.  I don't have an exact number of addresses when the issue occurs.  Locally, I'm only tracking 10 address or so but in my staging environment I'm tracking about 1.5k.

Thanks for any help!

**Comment by birozuru** [comment]
we host our own instance but still have those issues highlighted above.

**Comment by natsoni** [comment]
Oh okay, then there might be something failing with `track-address` when there are a lot of simultaneous subscriptions. 

Instead of making 1.5k `track-address` subscriptions for each address, have you tried to subscribe only once to `track-addresses` (this was introduced in https://github.com/mempool/mempool/pull/4137)?

Also note that it will be possible to use these subscriptions directly with mempool.js once https://github.com/mempool/mempool.js/pull/174 is merged.

**Comment by mononaut** [comment]
`track-address` only supports tracking a single address per websocket connection. Subsequent `{ "track-address": address }` messages *replace* the tracked address, or cancel the subscription if the provided address fails validation.

To track multiple addresses, you would need to use the new `track-addresses` subscription added in https://github.com/mempool/mempool/pull/4137, and connect to a mempool backend instance with a sufficiently high `config.MEMPOOL.MAX_TRACKED_ADDRESSES` configuration.
